-- Native Hyprland 0.55+ configuration.
require("variables")
require("monitors")
require("permissions")
require("ui")
require("workspaces")
require("input")
require("binds")
require("workspace-binds")
require("autostart")
